sudo: true
language: python
  - "2.7"

services:
  - docker
before_install:
  - docker pull debian:jessie

install:
  - docker run debian:jessie /bin/bash -c "wget -qO- https://github.com/clux/dotclux/archive/master.tar.gz | tar xz;"
  - docker run debian:jessie /bin/bash -c "TRAVIS=1 ./dotclux-master/desktop.sh"

notifications:
  email: false
