---
language: python
python:
- "2.7"
before_script:
- pip install yamllint
script:
- yamllint *.yml roles/
- test -z "$(find roles/ -type f -iname '*.yaml')" && echo "Extensions OK"
notifications:
  email:
    on_success: change
    on_failure: always
