---
- connection: local
  hosts: all
  vars_files:
  - vars/gogs.yml
  user: "{{ desktop_user }}"
  tasks:
  - template: src=templates/ssh_config.j2 dest=/home/{{ desktop_user }}/.ssh/config

  - name: Checkout secret modules
    git:
      repo=git@{{ gogs_name }}:{{ gogs_user }}/{{ item }}.git
      dest=/home/{{ desktop_user }}/{{ item }}
      key_file=/home/{{ desktop_user }}/.ssh/{{ gogs_ssh_id }}
      accept_hostkey=yes
      update=no
    with_items:
    - ssh
    - gpg
    - mumble
    #- cisco

  - name: install ssh
    shell: /home/{{ desktop_user }}/ssh/install.sh
    creates: /home/{{ desktop_user }}/.ssh/git

  - name: install ssh
    shell: /home/{{ desktop_user }}/gpg/install.sh
    creates: /home/{{ desktop_user }}/.gnupg/git

  - name: install mumble
    shell: /home/{{ desktop_user }}/mumble/install.sh
    creates: /home/{{ desktop_user }}/.config/Mumble

  - name: dotfiles
    git:
      repo=git@github.com:clux/dotfiles.git
      dest=/home/{{ desktop_user }}/dotfiles
      key_file=/home/{{ desktop_user }}/.ssh/id_github
      update=no
    notify: "install dotfiles"

  handlers:
  - name: install dotfiles
    shell: make config && make ui chdir=/home/{{ desktop_user }}/dotfiles
