---
- connection: local
  hosts: all
  vars_files:
  - vars/versions.yml
  user: "{{ desktop_user }}"
  gather_facts: True
  roles:
  - { role: arch, when: ansible_os_family == "Archlinux" }
  - fs
  - lpms
  - ssh
  - xdg
  - dev
