---
# Arch playbook - pacman install all the things

- name: Upgrade and update
  pacman: upgrade=yes update_cache=yes

# TODO: aur chrome

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
   # terminal tools
   - git
   - tig
   - rsync
   - bash-completion
   - cowsay
   - lolcat
   - ccze
   - rxvt-unicode
   - tmux
   - xterm
   # vim
   - vim
   - vim-ctrlp
   # chat
   - profanity
   - weechat
   # programming
   - python-pip
   - rust
   - cargo
   - ghc
   - cabal-install
   - shellcheck
   - cmake
   - clang
   - clang-analyzer
   - clang-tools-extra
   - lldb
   # system tools
   - htop
   - nmap
   - strace
   - lsb-release
   # network
   - vpnc
   - bind-tools # contains dig
   # dev services
   - docker
   - postgresql
   # ssh + secrets managers
   - keychain
   - pass
   - openssh
   # music
   - mpc
   - mpd
   - ncmpcpp
   # X related
   - gnome-screenshot
   - redshift
   - xclip
   - xdotool
   - xorg-xrandr
   - xorg-xrdb
   # gtk compat
   - gtk-engines
   - gtk-engine-murrine
   # browsers
   - chromium
   - firefox
   # video
   - libx264-10bit
   #- openshot
   - vlc
   # misc media
   - feh
   - gimp
   - gthumb
   - imagemagick
   - mumble
   # filesystems
   - ntfs-3g
   - nemo-fileroller
   - nemo-share
   - samba
   - mtpfs
   # gaming
   - steam
   - lib32-alsa-plugins
   - lib32-nvidia-libgl
   - nvidia-settings
   # fonts
   - ttf-ubuntu-font-family
