
# sanity
- file: path=/etc/portage/repos.conf state=directory
- file: path=/usr/local/bin state=directory

# portage settings
- template: src=templates/gentoo/make.conf.j2 dest=/etc/portage/make.conf
- template: src=templates/gentoo/gentoo.conf.j2 dest=/etc/portage/repos.conf/gentoo.conf

- name: Sync portage tree
  portage: sync="yes"
- name: Update portage
  portage: package=sys-apps/portage update=yes newuse=yes

# portage keywords and use flags
- file: src=templates/gentoo/package.keywords dest=/etc/portage/package.keywords/dotclux
- file: src=templates/gentoo/package.use dest=/etc/portage/package.use/dotclux
# TODO: package.license (for www-client/google-chrome)

# TODO: env-update

- portage: package={{ item }} update=yes newuse=yes
  with_items:
    - app-admin/sudo
    - app-admin/pass
    - app-editors/gedit
    - app-editors/nano
    - app-editors/vim
    - app-misc/tmux
    - app-portage/eix
    - app-portage/gentoolkit
    - app-shells/bash-completion # eselect bashcomp to enable
    - dev-lang/rust-bin
    - dev-libs/libbsd
    - dev-python/pip
    - dev-util/strace
    - dev-vcs/git
    - gnome-extra/cinnamon
    - media-fonts/dejavu
    - media-fonts/liberation-fonts
    - media-sound/mpc
    - media-sound/mpd
    - media-sound/ncmpcpp
    - net-misc/dhcpcd
    - net-misc/keychain
    - net-misc/netifrc
    - net-wireless/wpa_supplicant
    - sys-apps/lsb-release
    - sys-apps/pciutils
    - sys-boot/grub
    - sys-devel/distcc
    - sys-kernel/dracut
    - sys-kernel/gentoo-sources
    - sys-kernel/linux-firmware
    - www-client/firefox-bin
    - www-client/google-chrome
    - x11-apps/xrandr
    - x11-base/xorg-server
    - x11-drivers/xf86-input-evdev
    - x11-drivers/xf86-video-intel
    - x11-libs/gtk+extra
    - x11-misc/lightdm
    - x11-misc/lightdm-gtk-greeter
    - x11-misc/redshift
    - x11-misc/xclip
    - x11-terms/guake
    - x11-terms/rxvt-unicode # needs extra fonts
    - x11-terms/xterm
