---
# sshd

- template: src=templates/motd.sh dest=/etc/profile.d/motd.sh

- template: src=templates/sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
  - restart sshd

- service: name=sshd state=started enabled=yes
