---
# fstab for broxy

- name: mount ntfs disks
  mount:
    name: "/media/{{ item.name }}"
    src: "{{ item.src }}"
    fstype: ntfs-3g
    opts: "uid=bro,gid=users"
    state: mounted
  with_items:
  - { src: /dev/sdb1, name: dumptruck }
