---
# fstab for kjttks

- name: mount ntfs disks
  mount:
    name: "/media/{{ item.name }}"
    src: "{{ item.src }}"
    fstype: ntfs-3g
    opts: "uid=clux,gid=users"
    state: mounted
  with_items:
  - { src: /dev/sdb1, name: zeus }
  - { src: /dev/sdc3, name: zorn }

- name: mount ext4 disks
  mount:
    name: "/media/{{ item.name }}"
    src: "{{ item.src }}"
    fstype: ext4
    opts: "defaults,noatime"
    state: mounted
  with_items:
  - { src: /dev/sdd2, name: gauss }
