---
# aur installs

- name: clone aur repos
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: /home/{{ desktop_user }}/local/{{ item }}
    update: "{{ upgrade_tasks | default(false) }}"
  with_items:
  - google-chrome
  - discord
  - ctop
  - z

- name: Install aur packages
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/{{ item.repo }}
    creates: "{{ item.dest }}"
    executable: /bin/bash
  with_items:
  #- { repo: google-chrome, dest: /usr/bin/google-chrome-stable }
  - { repo: z, dest: /usr/share/z/z.sh }
  - { repo: discord, dest: /sbin/discord }
  - { repo: ctop, dest: /sbin/ctop }

- name: Checkout personal pkgbuilds
  git:
    repo: git@github.com:clux/pkgbuilds.git
    dest: /home/{{ desktop_user }}/repos/pkgbuilds
    key_file: /home/{{ desktop_user }}/.ssh/id_github
    update: "{{ upgrade_tasks | default(false) }}"

- name: Install personal packages
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/repos/pkgbuilds/{{ item.pkg }}
    creates: "{{ item.dest }}"
    executable: /bin/bash
  with_items:
  - { pkg: nodejs-lts, dest: /sbin/node }
