---
# aur installs

- name: clone aur repos
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: /home/{{ desktop_user }}/local/{{ item }}
    update: "{{ upgrade_tasks | default(false) }}"
  with_items:
  - google-chrome
  - discord
  - ctop

- name: Install aur packages
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/{{ item.repo }}
    creates: "{{ item.dest }}"
    executable: /bin/bash
  with_items:
  #- { repo: google-chrome, dest: /usr/bin/google-chrome-stable }
  - { repo: discord, dest: /sbin/discord }
  - { repo: ctop, dest: /sbin/ctop }
