---
# aur installs

- name: Checkout personal pkgbuilds
  git:
    repo: git@github.com:clux/pkgbuilds.git
    dest: /home/{{ user }}/repos/pkgbuilds
    key_file: /home/{{ user }}/.ssh/id_github
    update: "{{ upgrade_tasks | default(false) }}"

# NB: this needs shell over command as it may ask for sudo mid item
- name: Install personal packages
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ user }}/repos/pkgbuilds/{{ item.pkg }}
    creates: "{{ item.dest }}"
    executable: /bin/bash
  with_items:
  - { pkg: blackbox-vcs, dest: /sbin/blackbox_edit }
  - { pkg: sublime-text-dev, dest: /sbin/subl3 }
  - { pkg: ctop, dest: /sbin/ctop }
  - { pkg: libc++, dest: /usr/lib/libc++.so }
  - { pkg: discord, dest: /sbin/discord }
  - { pkg: z, dest: /usr/share/z/z.sh }
  - { pkg: shellcheck-static, dest: /sbin/shellcheck }
  - { pkg: alacritty-git, dest: /sbin/alacritty }
  # Commented out chrome as I'm trying to live with chromium instead
  #- { pkg: google-chrome, dest: /sbin/google-chrome-stable }
  # Commented out roccat drivers as Kone Pure Owleye is not recognized
  # Also, not really necessary as default settings are fine.
  #- { pkg: libgaminggear, dest: /sbin/gaminggearfxinfo } # needed for all roccat-tools*
  #- { pkg: roccat-tools-konepure, dest: /sbin/roccatkonepureconfig }
