---
- name: Install rust
  shell: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --no-modify-path -y
  args:
    creates: "/home/{{ desktop_user }}/.cargo/bin/rustc"
    executable: /bin/bash
  when: upgrade_tasks | default(false)

- name: Upgrade rustup
  shell: rustup self update
  when: upgrade_tasks | default(false)

- name: Upgrade rust stable
  shell: rustup update stable
  when: upgrade_tasks | default(false)

- name: Upgrade rust nightly
  shell: rustup update nightly
  when: upgrade_tasks | default(false)
