---
# Core Arch Linux Setup

- import_tasks: pacman.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]

#- import_tasks: aur.yml
#  when: ansible_os_family == "Archlinux"
#  become: no
#  tags: [arch, aur]

- import_tasks: services.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]

- import_tasks: systemd.yml
  when: ansible_os_family == "Archlinux"
  become: yes
  tags: [arch, core]
