---
# pacman interface

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
  # terminal tools
  - git
  - bc
  - tig
  - rsync
  - bash-completion
  - cowsay
  - lolcat
  - ccze
  - rxvt-unicode
  - tmux
  - xterm
  - jshon
  - bash-bats
  - shellcheck
  - vim
  # chat
  - profanity
  - weechat
  # programming
  - python-pip
  - ipython
  - cmake
  - clang
  - clang-tools-extra
  - llvm
  - lldb
  # system tools
  - htop
  - strace
  - community/perf
  # network
  - vpnc
  - nmap
  - bind-tools  # contains dig
  # dev services
  - docker
  - postgresql
  # ssh + secrets managers
  - keychain
  - pass
  - openssh
  # music
  - mpc
  - mpd
  - ncmpcpp
  # X related
  - gnome-screenshot
  - redshift
  - xclip
  - xdotool
  - xorg-xrandr
  - xorg-xinput
  - xorg-xrdb
  # gtk compat
  - gtk-engines
  - gtk-engine-murrine
  # cinnamon addons
  - dconf-editor
  # browsers
  - chromium
  - firefox
  # video
  - vlc
  # misc media
  - feh
  - gimp
  - gthumb
  - imagemagick
  - mumble
  - gedit
  # filesystems
  - ntfs-3g
  - nemo-fileroller
  - nemo-share
  - samba
  - mtpfs # kindle
  # gaming
  - steam
  - lib32-alsa-plugins
  # fonts
  - ttf-ubuntu-font-family
  - otf-ipafont # japanese
  - adobe-source-han-sans-kr-fonts # korean
  - ttf-tlwg # thai
  - wqy-microhei # chinese
  - noto-fonts-emoji # work is serious business
