---
# pacman interface

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
  # terminal tools
  - git
  - bc
  - tig
  - rsync
  - bash-completion
  - cowsay
  - lolcat
  - ccze
  - tmux
  - xterm
  - jq
  - bash-bats
  - ripgrep
  - exa
  - tokei
  - fd
  - fzf
  - vim
  - asciinema
  - terraform
  - task
  - datamash
  # social
  - profanity
  - weechat
  - hugo
  # music
  - musescore
  # programming
  - python-pip
  - ipython
  - cmake
  - clang
  - compiler-rt
  - llvm
  - lldb
  - musl
  - postgresql-libs # for diesel cli
  - go
  - nodejs
  - npm
  - yarn
  - rustup
  # system tools
  - htop
  - strace
  - perf
  - lsof
  # network
  - strongswan
  - nmap
  - net-tools # netstat
  - bind-tools  # contains dig
  - traceroute
  - bmon
  - bandwhich
  - nethogs
  - trickle
  # wifi
  - iw
  - create_ap
  # dev services
  - docker
  - docker-compose
  - minikube
  # ssh + secrets managers
  - keychain
  - keybase
  - pass
  - openssh
  # music
  - mpc
  - mpd
  - ncmpcpp
  # ebooks
  - poppler
  - calibre
  # chromecast - see https://wiki.archlinux.org/index.php/VLC_media_player#Chromecast_support to enable mdns
  - libmicrodns
  - protobuf
  # X related
  - gnome-screenshot
  - redshift
  - xclip
  - xdotool
  - xorg-xrandr
  - xorg-xinput
  - xorg-xrdb
  # gtk compat
  - gtk-engines
  - gtk-engine-murrine
  # cinnamon addons
  - dconf-editor
  # browsers
  - chromium
  - firefox
  # media
  - vlc
  - feh
  - gimp
  - gthumb
  - imagemagick
  - gedit
  - gphoto2
  - peek
  # filesystems
  - ntfs-3g
  - nemo-fileroller
  - nemo-share
  - samba
  - mtpfs # kindle
  - android-file-transfer
  - gptfdisk
  # fonts
  - ttf-ubuntu-font-family
  - otf-ipafont # japanese
  - adobe-source-han-sans-kr-fonts # korean
  - fonts-tlwg # thai
  - wqy-microhei # chinese
  - noto-fonts-emoji # google's emoji font
  - ttf-symbola # unicode font for github style emojis

# Linux capabilities so some apps can run sans-sudo
- capabilities: path=/sbin/nethogs capability=cap_net_admin+ep
- capabilities: path=/sbin/nethogs capability=cap_net_raw+ep
- capabilities: path=/sbin/bandwhich capability=cap_net_raw,cap_net_admin+ep

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
  - steam
  - steam-native-runtime
  when: inventory_hostname == "kjttks"

# Extra weird autocompletion stuff
- name: Hugo completion
  shell: hugo gen autocomplete --completionfile=/usr/share/bash-completion/completions/hugo
  args:
    creates: /usr/share/bash-completion/completions/hugo
