---
# pacman interface

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
  # terminal tools
  - git
  - bc
  - tig
  - rsync
  - bash-completion
  - cowsay
  - lolcat
  - ccze
  - tmux
  - xterm
  - jshon
  - bash-bats
  - the_silver_searcher
  - ripgrep
  - fzf
  - vim
  - asciinema
  # chat
  - profanity
  - weechat
  # music
  - musescore
  # programming
  - python-pip
  - ipython
  - cmake
  - clang
  - clang-tools-extra
  - llvm
  - lldb
  - go
  - nodejs-lts-boron
  - npm
  - yarn
  - rustup
  # system tools
  - htop
  - strace
  - perf
  - lsof
  # network
  - vpnc
  - nmap
  - net-tools # netstat
  - bind-tools  # contains dig
  - traceroute
  - bmon
  - nethogs
  # dev services
  - docker
  - docker-compose
  # ssh + secrets managers
  - keychain
  - pass
  - openssh
  # music
  - mpc
  - mpd
  - ncmpcpp
  # X related
  - gnome-screenshot
  - redshift
  - xclip
  - xdotool
  - xorg-xrandr
  - xorg-xinput
  - xorg-xrdb
  # gtk compat
  - gtk-engines
  - gtk-engine-murrine
  # cinnamon addons
  - dconf-editor
  # browsers
  - chromium
  - firefox
  # media
  - vlc
  - feh
  - gimp
  - gthumb
  - imagemagick
  - gedit
  - gphoto2
  # filesystems
  - ntfs-3g
  - nemo-fileroller
  - nemo-share
  - samba
  - mtpfs # kindle
  - android-file-transfer
  - gptfdisk
  # fonts
  - ttf-ubuntu-font-family
  - otf-ipafont # japanese
  - adobe-source-han-sans-kr-fonts # korean
  - fonts-tlwg # thai
  - wqy-microhei # chinese
  - noto-fonts-emoji # google's emoji font
  - ttf-symbola # unicode font for github style emojis

# Linux capabilities so some apps can run sans-sudo
- capabilities: path=/sbin/nethogs capability=cap_net_admin+ep
- capabilities: path=/sbin/nethogs capability=cap_net_raw+ep

- name: Install dependencies
  pacman: name={{ item }} state=installed
  with_items:
  - steam
  - steam-native-runtime
  when: inventory_hostname != "ealbrigt-ws"
