---
# systemd overrides

- name: Ensure Configuration Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/systemd/system/docker.service.d

- name: systemd overrides
  template:
    src: "templates/{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
  with_items:
  - { src: docker.service.override, dest: docker.service.d/override.conf }
