---
# install rust components via rustup and cargo

- name: Install rustup
  pacman: name=rustup state=installed

- name: Default toolchain
  shell: rustup default stable
  # TODO: this only needs to be done when rustc / cargo does not have a toolchain yet

- name: rustup updates
  shell: rustup {{ item }}
  when: upgrade_tasks | default(false)
  register: command_result
  changed_when:
  - "'downloading' in command_result.stderr"
  with_items:
  - "update stable"
  - "update nightly"
  - "component add rust-src"
  - "component add rls --toolchain nightly"
  - "component add rust-analysis --toolchain nightly"
  - "component add rust-src --toolchain nightly"

- name: install modules on rustup stable
  shell: cargo install {{ item }} --force
  when: recompile_tasks | default(false)
  with_items:
  - rustfmt
  - racer
  - tokei
  - cargo-edit

- name: install modules on rustup nightly
  shell: rustup run nightly cargo install clippy --force
  when: recompile_tasks | default(false)

- name: Link rustc-stable to rustup stable source location (I point racer there)
  file:
    src="/home/{{ desktop_user }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust"
    dest="/home/{{ desktop_user }}/.cargo/rustc-stable"
    state=link
    force=yes
