---
# cargo playbook - install rust toolchain and cargo modules

- name: Install rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --no-modify-path -y
  args:
    creates: "/home/{{ desktop_user }}/.cargo/bin/rustup"
    executable: /bin/bash

# all toolchain upgrades retrieved on full upgrades
- name: Upgrade rustup
  shell: rustup self update
  when: upgrade_tasks | default(false)

- name: Upgrade rust stable
  shell: rustup update stable
  when: upgrade_tasks | default(false)

- name: Upgrade rust nightly
  shell: rustup update nightly
  when: upgrade_tasks | default(false)

- name: Nightly rust for clippy
  shell: rustup update nightly-2017-03-28
  when: upgrade_tasks | default(false)

# module installs via cargo
- name: install modules on rustup stable
  shell: cargo install {{ item }} --force
  when: recompile_tasks | default(false)
  with_items:
  - rustfmt
  - racer
  - tokei
  - cargo-edit

- name: install modules on rustup nightly
  shell: rustup run nightly-2017-03-28 cargo install clippy --force
  when: recompile_tasks | default(false)

# rust lang source code for racer
- name: Grab rust source tarball
  get_url:
    url=https://static.rust-lang.org/dist/rustc-{{ rust_ver }}-src.tar.gz
    dest=/home/{{ desktop_user }}/.cargo/rustc-{{ rust_ver }}-src.tar.gz
  register: rustc_tarball

- name: Extract rust source
  unarchive:
    copy: no
    src: "{{ rustc_tarball.dest }}"
    dest: /home/{{ desktop_user }}/.cargo/
    creates: /home/{{ desktop_user }}/.cargo/rustc-{{ rust_ver }}

- name: Link current as latest
  file:
    src="/home/{{ desktop_user }}/.cargo/rustc-{{ rust_ver }}-src"
    dest="/home/{{ desktop_user }}/.cargo/rustc-stable"
    state=link
    force=yes
