---
# install rust components via rustup and cargo

- name: rustup updates
  command: rustup {{ item }}
  when: upgrade_tasks | default(false)
  register: command_result
  changed_when:
  - "'downloading' in command_result.stderr"
  with_items:
  - "update stable"
  - "update nightly"
  - "component add rust-src"
  - "component add rls --toolchain nightly"
  - "component add rust-analysis --toolchain nightly"
  - "component add rust-src --toolchain nightly"

- name: rustup default stable
  command: rustup default stable
  register: rustup_result
  changed_when: "'unchanged' not in rustup_result.stdout"

- name: install modules on rustup stable
  command: cargo install {{ item }} --force
  when: recompile_tasks | default(false)
  with_items:
  - rustfmt
  - racer
  - tokei
  - cargo-edit
  - cargo-tarpaulin

- name: install modules on rustup nightly
  command: rustup run nightly cargo install clippy --force
  when: recompile_tasks | default(false)

- name: Link rustc-stable to rustup stable source location (I point racer there)
  file:
    src="/home/{{ desktop_user }}/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust"
    dest="/home/{{ desktop_user }}/.cargo/rustc-stable"
    state=link
    force=yes
