---
# installs from language specific package managers

- include: npm.yml
  tags: [lpms, npm, core]

- include: pip.yml
  tags: [lpms, pip, core]

- include: gem.yml
  tags: [lpms, gem, core]

- include: cargo.yml
  tags: [lpms, cargo, core]

- include: goget.yml
  tags: [lpms, go, core]
