---
# npm playbook - install cli tools globally

- name: have your ex help your new gf move in
  npm: name=yarn global=yes

- name: Install global npm dependencies (via yarn)
  shell: yarn global add {{ item }}
    creates={{node_prefix}}/node/bin/{{ item }}
  # TODO: Should have a way to upgrade these without editing this file..
  with_items:
  - badgify
  - faucet
  - eslint
  - jshint
  - jsonlint
  - json
  - js-yaml
  - pkginit
  - browserify
  - asciify
  - ytdl
  - symlink
  - bower
  - pm2
  - marked-man
  - yr-cli
  - zalgolize

- file: path=/home/{{ desktop_user }}/.config/pkginit/ state=directory
- template:
    src=templates/pkg.json
    dest=/home/{{ desktop_user }}/.config/pkginit/default.json
