---
# npm playbook - install cli tools globally

# Assume these are stable enough to not have to do state=latest on them
- name: Install npm dependencies
  npm: name={{ item }} global=yes
  with_items:
  - badgify
  - faucet
  - eslint
  - jshint
  - jsonlint
  - json
  - js-yaml
  - pkginit
  - browserify
  - asciify
  - ytdl
  - symlink
  - bower
  - pm2
  - marked-man
  - yr-cli
  - zalgolize

- file: path=/home/{{ desktop_user }}/.config/pkginit/ state=directory
- template:
    src=templates/pkg.json
    dest=/home/{{ desktop_user }}/.config/pkginit/default.json
