---
# npm playbook - install cli tools globally

- name: npm config set prefix ~/.node_modules
  lineinfile:
    dest: /home/{{ user }}/.npmrc
    regexp: '^prefix='
    line: 'prefix=/home/{{ user }}/.node_modules'

- set_fact:
    npm_state: "{{ 'latest' if (upgrade_tasks | default(false)) else 'present' }}"

- name: Install global npm dependencies
  npm: name={{ item }} state={{ npm_state }} global=true
  with_items:
  - badgify
  - faucet
  - eslint
  - jshint
  - jsonlint
  - pkginit
  - asciify
  - marked-man
  - yr-cli
  - zalgolize

- name: broxy global modules
  when: inventory_hostname == "broxy"
  npm: name={{ item }} state={{ npm_state }} global=true
  with_items:
  - pm2

- file: path=/home/{{ user }}/.config/pkginit/ state=directory
- template:
    src=templates/pkg.json
    dest=/home/{{ user }}/.config/pkginit/default.json
