---
# npm playbook - install cli tools globally

- name: npm config set prefix ~/.node_modules
  lineinfile:
    dest: /home/{{ user }}/.npmrc
    regexp: '^prefix='
    line: 'prefix=/home/{{ user }}/.node_modules'

- name: Install global npm dependencies
  npm: name={{ item }} state=present global=true
  with_items:
  - badgify
  - faucet
  - eslint
  - jshint
  - jsonlint
  - json
  - js-yaml
  - pkginit
  - asciify
  - marked-man
  - yr-cli
  - zalgolize

- name: broxy global modules
  when: inventory_hostname == "broxy"
  npm: name={{ item }} state=present global=true
  with_items:
  - pm2

- file: path=/home/{{ user }}/.config/pkginit/ state=directory
- template:
    src=templates/pkg.json
    dest=/home/{{ user }}/.config/pkginit/default.json
