---
# pip playbook - install cli tools in pip user dir

# NB: pip is managed by pacman

# Some of these technically do exist as well in pacman, but want some updates faster
- name: Install dependencies
  pip: name={{ item }} extra_args='--user' state=latest
  with_items:
  - ghp-import
  - pyflakes
  - pylint
  - pyaml
  - yq
  - requests
  - yamllint
  - youtube-dl
  - awscli
  - python-openstackclient
  - pipenv
  - pytest

- name: Install from gemfury
  pip: name={{ item }} extra_args='--user --extra-index-url={{ lookup('passwordstore', 'babylon/gemfury-index-url') }}' state=latest
  with_items:
  - kongtokens
