---
# clone playbook - install stuff from git tags / source trees

- file: path=/home/{{ desktop_user }}/local/{{ item }} state=directory
  with_items:
  - share/man/man1
  - bin

- name: Install blackbox
  git:
    repo: https://github.com/StackExchange/blackbox
    dest: /home/{{ desktop_user }}/local/blackbox
    version: stable
    update: "{{ upgrade_tasks | default(false) }}"
  notify: make-install blackbox

# Exists on AUR as z, but not on debian
- name: Install z
  git:
    repo: https://github.com/rupa/z
    dest: /home/{{ desktop_user }}/local/z
    update: "{{ upgrade_tasks | default(false) }}"

- name: Install vim vundle - allows :PluginInstall
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: /home/{{ desktop_user }}/.vim/bundle/Vundle.vim
    update: "{{ upgrade_tasks | default(false) }}"

# only thing z needs to install is z.1
# otherwise relies on sourcing ./z/z.sh from bash_profile
- name: link z.1
  file:
    src=/home/{{ desktop_user }}/local/z/z.1
    dest=/home/{{ desktop_user }}/local/share/man/man1/z.1
    state=link
    force=yes
