---
# clone playbook - install stuff from git tags / source trees

- file: path=/home/{{ desktop_user }}/local/{{ item }} state=directory
  with_items:
  - share
  - bin

- name: Clone blackbox
  git:
    repo: https://github.com/StackExchange/blackbox
    dest: /home/{{ desktop_user }}/local/blackbox
    version: stable
    update: "{{ upgrade_tasks | default(false) }}"

- name: make-install blackbox
  shell: make manual-install
  args:
    chdir: /home/{{ desktop_user }}/local/blackbox/
    creates: "/usr/local/bin/blackbox_cat"
    executable: /bin/bash
