---
# NB: this is installed from pkgbuild step in roles/arch/tasks/aur

#- name: add node path to all users
#  lineinfile:
#    dest=/etc/profile
#    line="export PATH={{node_prefix}}/node/bin:$PATH"
#  become: yes
#
#- name: Downgrade npm to @2.*
#  npm: name=npm global=yes version=2
