---
# roccat mouse tools

# Configuration made can be stored on the device
# so this step is not necessary unless you need to customize
# Documentation at http://roccat.sourceforge.net/general.html
# NB: roccat-tools depends on specific versions of libgaminggear

- name: Clone libgaminggear and roccat-tools
  git:
    repo: https://aur.archlinux.org/{{ item }}.git
    dest: /home/{{ desktop_user }}/local/{{ item }}
    update: "{{ upgrade_tasks | default(false) }}"
  with_items:
    - libgaminggear
    - roccat-tools

- name: Install libgaminggear
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/libgaminggear/
    creates: /usr/bin/gaminggearfxinfo
    executable: /bin/bash

- name: Install roccat-tools
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/roccat-tools/
    creates: /usr/bin/roccatkonepureconfig
    executable: /bin/bash

# Can then run `sudo roccatkonepureconfig` and configure
