---
# roccat mouse tools

# Configuration made can be stored on the device
# so this step is not necessary unless you need to customize
# Documentation at http://roccat.sourceforge.net/general.html

- name: Clone libgaminggear
  git:
    repo: https://aur.archlinux.org/libgaminggear.git
    dest: /home/{{ desktop_user }}/local/libgaminggear
    update: "{{ upgrade_tasks | default(false) }}"

- name: Clone roccat-tool
  git:
    repo: https://aur.archlinux.org/roccat-tools.git
    dest: /home/{{ desktop_user }}/local/roccat-tools
    update: "{{ upgrade_tasks | default(false) }}"

- name: Install libgaminggear
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/libgaminggear/
    creates: /usr/bin/gaminggearfxinfo
    executable: /bin/bash
  become: yes

- name: Install roccat-tools
  shell: makepkg -si --noconfirm
  args:
    chdir: /home/{{ desktop_user }}/local/roccat-tools/
    creates: /usr/bin/gaminggearfxinfo
    executable: /bin/bash
  become: yes

# Can then run `sudo roccatkonepureconfig` and configure
