---
# docker conditionals

- import_tasks: clux.yml
  when: inventory_hostname != "broxy"
  become: no
  tags: [docker, core]

- import_tasks: broxy.yml
  when: inventory_hostname == "broxy"
  become: no
  tags: [docker, core]
