---
# Clone all active projects into ~/repos

- file: path=/home/{{ desktop_user }}/{{ item }} state=directory
  with_items:
  - repos
  - repos/tournament
  - repos/interlude
  - sqbu

- name: Checkout general modules
  git:
    repo=git@github.com:clux/{{ item }}.git
    dest=/home/{{ desktop_user }}/repos/{{ item }}
    key_file=/home/{{ desktop_user }}/.ssh/id_github
    update=no
  with_items:
  - bandage
  - blog
  - deus-login
  - food
  - icebreaker
  - muslrust
  - posts
  - sdp-transform
  - quadratic

- name: Checkout tournament modules
  git:
    repo=git@github.com:clux/{{ item }}.git
    dest=/home/{{ desktop_user }}/repos/tournament/{{ item }}
    key_file=/home/{{ desktop_user }}/.ssh/id_github
    update=no
  with_items:
  - duel
  - duel-names
  - ffa
  - ffa-tb
  - group
  - groupstage
  - groupstage-tb
  - groupstage-tb-duel
  - masters
  - roundrobin
  - tiebreaker
  - tournament
  - tourney

- name: "Link node modules"
  command: symlink ~/repos ~/repos/tournament --execute
