---
# file system conditionals

- include_tasks: kjttks.yml
  when: inventory_hostname in ["kjttks"]
  tags: [disks, core]

- include_tasks: broxy.yml
  when: inventory_hostname in ["broxy"]
  tags: [disks, core]
