---
# docker services for broxy

# docker create --name=gogs -p 8722:22 -p 8880:3000 -v ~/gogs:/data gogs/gogs
- name: Run gogs service
  docker_container:
    name: gogs
    image: gogs/gogs
    state: started
    volumes:
    - "/home/bro/gogs:/data"
    ports:
    - "8722:22"
    - "8880:3000"
